# Generated by Django 3.0.2 on 2020-01-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Post',
        ),
    ]
